### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [armaldio/BulbHub#1]
Greetings, I just made a logo for your project, hope you like it.
![bulb1](https://user-images.githubusercontent.com/35619342/39702143-cc07a614-51d1-11e8-8c42-3b1c98635e8f.png)
If you liked it, let me know which variation and I'll upload the files on a PR. 
Please tell me if you want me to add/modify something.

**Comment by armaldio** [comment]
Hey @michaelizer 

I'm really surprised to see someone on this project since I just started it ^^
How did you get there ?

Thanks for your proposition!
I think I really like the blue variation. Both with background and without. I think we can use both in different places like favicon or mainpage

**Comment by michaelizer** [comment]
Hahah I'm just going through GitHub, looking for interesting projects to collaborate with designs.
Here you are [#2](https://github.com/armaldio/BulbHub/pull/2)

**Comment by armaldio** [comment]
Really cool, glad you stopped here ;)
So you're a designer ? only for icons and graphics or do you also know UX ?
It could be really cool if you're interested with the project to collaborate to make a good UX

**Comment by michaelizer** [comment]
Only for Icons now. Maybe in the future, why not? but I need to keep practicing hehe

**Comment by armaldio** [comment]
OK, then. I hope you will enjoy making icons ;)
